app:
  replicas: 1
  name: offer-management-ms
  configPath: /app/config
  port: 8087
configMap:
  name: offer-management-config

image:
  repository: abw12/offer-management-ms # update image name
  tag: v1
postgres:
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  host: db-postgresql-blr1-67863-do-user-15872635-0.c.db.ondigitalocean.com
  port: 25061
  db: absolutehealth
