apiVersion: v1
kind: Service
metadata:
  name: offer-mgmt-ms
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.app.port }}
  type: ClusterIP